### ISSUE TITLE
Cannot import name 'asyncio'

### ISSUE THREAD

**Issue by richardyang** [Maselkov/Toothy#2]
Hi there, I followed the setup instructions for Toothy on Ubuntu 16.04, and I get this error from run.py:

```
File "run.py", line 5, in <module>
from toothy.toothy import Toothy
File "/home/richard/Toothy/toothy/toothy.py", line 5, in <module>
from .database import MongoController
File "/home/richard/Toothy/toothy/database.py", line 3, in <module>
from motor.motor_asyncio import AsyncIOMotorClient
File "/home/richard/.local/lib/python3.6/site-packages/motor/motor_asyncio.py", line 18, in <module>
from .frameworks import asyncio as asyncio_framework
ImportError: cannot import name 'asyncio'
```

First, I used Python 3.5 with discord.py and motor installed, and mongoDB running. I thought it might have been a version issue, so I also tried with Python 3.6, but did not resolve. 

Any help would be appreciated, thank you.

**Comment by Maselkov** [comment]
Check your python installation and motor installation, maybe try reinstalling. I just tested it on a fresh install with python3.6, and it's working for me.

**Comment by richardyang** [comment]
Thanks for the fast response! I just reinstalled Python3.5, pymongo 3.5, and Motor 1.1 (instead of 1.2) and it fixed it.
