### ISSUE TITLE
How to config mongoDB?

### ISSUE THREAD

**Issue by richardyang** [Maselkov/Toothy#3]
Hi there. I'm new to using mongoDB, but I read up on some tutorials, and I'm not sure how to edit config.json.

Say I'm using admin as the authentication database, and I've created a new user named toothy with the role userAdminAnyDatabase, would I configure it as follows:
```
        "credentials": {
            "user": toothy,
            "pass": thepasswordhere,
            "authentication_db": "admin"
        }
```

When I did this, I got an error from pymongo: `pymongo.errors.OperationFailure: not authorized on toothy to execute command { find: "configs", filter: { cog_name: "Global " }, limit: 1, singleBatch: true }`

Do I need to create a new database named toothy and then make a user toothy.toothy with the role admin? 

Thanks in advance!

**Comment by Maselkov** [comment]
The user needs a readWrite role on the database as well

**Comment by richardyang** [comment]
I'm still getting the same error, after granting readWrite. This is what my db.getUsers() responds with:
```
> db.getUsers()
[
        {
                "_id" : "admin.admin",
                "user" : "admin",
                "db" : "admin",
                "roles" : [
                        {
                                "role" : "root",
                                "db" : "admin"
                        }
                ]
        },
        {
                "_id" : "admin.toothy",
                "user" : "toothy",
                "db" : "admin",
                "roles" : [
                        {
                                "role" : "readWrite",
                                "db" : "admin"
                        },
                        {
                                "role" : "userAdminAnyDatabase",
                                "db" : "admin"
                        }
                ]
        }
]
```

**Comment by Maselkov** [comment]
Currently it has readWrite access to `admin` database. it needs to have it for `toothy`
```js
use admin
db.grantRolesToUser(
    "toothy",
    [ { role: "readWrite", db: "toothy" } ]
)
